/**
 * Injects package.json version into the app and PWA artifacts.
 * Run before dev/build (prebuild / predev). Reads BASE_PATH from env for deploy base (e.g. /CallerBuddy/).
 */
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const version = pkg.version;

// Base path for deployed app (e.g. '' or '/CallerBuddy'). No trailing slash.
const basePath = (process.env.BASE_PATH || "").replace(/\/?$/, "") || "";
const rootUrl = basePath ? basePath + "/" : "/";
const cacheUrls = [rootUrl, rootUrl + "index.html"];

// 1) src/version.ts
fs.writeFileSync(
  path.join(root, "src", "version.ts"),
  `/** Generated by scripts/inject-version.cjs - do not edit by hand */\nexport const APP_VERSION = "${version}";\n`
);

// 2) manifest.json
const manifestPath = path.join(root, "public", "manifest.json");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
manifest.version = version;
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));

// 3) public/sw.js with versioned cache name and correct cache URLs
const cacheName = `callerbuddy-v${version.replace(/[^a-z0-9.-]/gi, "-")}`;
const swContent = `const CACHE_NAME = "${cacheName}";
const CACHE_URLS = ${JSON.stringify(cacheUrls)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(CACHE_URLS))
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    })
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  if (event.request.url.startsWith(self.location.origin)) {
    event.respondWith(
      caches.match(event.request).then((cached) => {
        return cached ?? fetch(event.request);
      })
    );
  }
});
`;
fs.writeFileSync(path.join(root, "public", "sw.js"), swContent);

console.log("Injected version:", version, basePath ? `(base: ${basePath})` : "");
