/**
 * Injects package.json version into the app and PWA artifacts.
 * Run before dev/build (prebuild / predev). Reads BASE_PATH from env for deploy base (e.g. /CallerBuddy/).
 */
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const baseVersion = pkg.version;
// Append build timestamp so each dev/build run shows a unique version in the UI
const now = new Date();
const stamp = `${now.getMonth() + 1}/${now.getDate()}-${now.getHours()}:${String(now.getMinutes()).padStart(2, "0")}`;
const version = `${baseVersion}-${stamp}`;

// Base path for deployed app (e.g. '' or '/CallerBuddy'). No trailing slash.
const basePath = (process.env.BASE_PATH || "").replace(/\/?$/, "") || "";

// 1) src/version.ts
fs.writeFileSync(
  path.join(root, "src", "version.ts"),
  `/** Generated by scripts/inject-version.cjs - do not edit by hand */\nexport const APP_VERSION = "${version}";\n`
);

// manifest.json and sw.js are generated by the Vite plugin from version.ts + templates

console.log("Injected version:", version, basePath ? `(base: ${basePath})` : "");
